spring:
  application:
    name: hotel-api

  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: user
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    default-schema: public
#    contexts: all
#    labels: all

server:
  port: 8092
  servlet:
    contextPath: /property-view
  error:
    include-message: always
    include-binding-errors: always